services:
    pgdb:
        image: postgres:14
        container_name: pgdb
        volumes:
            - pgdb_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:5432"
        networks:
            - app-network

    core:
        build:
            context: ./core
            dockerfile: Dockerfile
        container_name: core
        volumes:
            - ./core:/home/app/core
            - static_volume:/home/app/core/static
            - media_volume:/home/app/core/media
        expose:
            - "8000"
        environment:
            # role for entrypoint
            - ROLE=core
            # basic settings
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            #  database configuration
            - PGDB_ENGINE=${PGDB_ENGINE}
            - PGDB_NAME=${PGDB_NAME}
            - PGDB_USER=${PGDB_USER}
            - PGDB_PASSWORD=${PGDB_PASSWORD}
            - PGDB_HOST=${PGDB_HOST}
            - PGDB_PORT=${PGDB_PORT}
        depends_on:
            - pgdb
        restart: always
        networks:
            - app-network

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/home/app/core/static
            - media_volume:/home/app/core/media
        depends_on:
            - core
        restart: always
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    static_volume:
    media_volume:
    pgdb_data:
