services:
    redis:
        container_name: redis
        image: redis:7.4
        ports:
            - "6379:6379"
        command: redis-server --save 60 1 --loglevel warning

    backend:
        build:
            context: ./core
            dockerfile: Dockerfile.dev
        container_name: backend
        volumes:
            - ./core:/usr/src/app
        ports:
            - "127.0.0.1:8000:8000"
        environment:
            # basic settings
            - SECRET_KEY=test
            - DEBUG=True
            - DJANGO_SETTINGS_MODULE=core.settings
            # password reset timeout for api v1
            - PASSWORD_RESET_TIMEOUT=120
            # email confirguration
            - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
            - EMAIL_HOST=smtp4dev
            - EMAIL_PORT=25
            - EMAIL_USE_TLS=True
            - EMAIL_HOST_USER=
            - EMAIL_HOST_PASSWORD=
            #  database configuration
            - DB_ENGINE=django.db.backends.sqlite3
            - DB_NAME=/usr/src/app/db.sqlite3
        depends_on:
            - redis
        restart: always

    smtp4dev:
        image: rnwood/smtp4dev:v3
        restart: always
        ports:
            # Change the number before : to the port the web interface should be accessible on
            - "127.0.0.1:5000:80"
            # Change the number before : to the port the SMTP server should be accessible on
            - "25:25"
            # Change the number before : to the port the IMAP server should be accessible on
            - "143:143"
        volumes:
            # This is where smtp4dev stores the database..
            - smtp4dev-data:/smtp4dev
        environment:
            #Specifies the URLs the web UI will use inside the container.
            - ServerOptions__Urls=http://*:80

            #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
            - ServerOptions__HostName=smtp4dev

volumes:
    smtp4dev-data:
