services:
    postgres:
        image: postgres:14
        container_name: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:5432"

    backend:
        build:
            context: ./core
            dockerfile: Dockerfile.prod
        container_name: backend
        volumes:
            - ./core:/home/app/core
            - static_volume:/home/app/core/static
            - media_volume:/home/app/core/media
        expose:
            - "8000"
        environment:
            # role for entrypoint
            - ROLE=backend
            # basic settings
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            #  database configuration
            - PGDB_ENGINE=${PGDB_ENGINE}
            - PGDB_NAME=${PGDB_NAME}
            - PGDB_USER=${PGDB_USER}
            - PGDB_PASSWORD=${PGDB_PASSWORD}
            - PGDB_HOST=${PGDB_HOST}
            - PGDB_PORT=${PGDB_PORT}

        depends_on:
            - postgres
        restart: always

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/home/app/core/static
            - media_volume:/home/app/core/media
        depends_on:
            - backend
        restart: always

volumes:
    static_volume:
    media_volume:
    postgres_data:
