# Generated by Django 4.2.16 on 2024-11-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referraltoken",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="referraltoken",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
