# Generated by Django 4.2.16 on 2024-11-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("referral", "0002_alter_referraltoken_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralrelationship",
            name="first_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relation_first_name",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="last_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relation_last_name",
                to="accounts.profile",
            ),
        ),
    ]
