# Generated by Django 4.2.16 on 2024-11-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("referral", "0003_alter_referralrelationship_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referralrelationship",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="referralrelationship",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="refer_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals_made",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="refer_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals_received",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="referralrelationship",
            name="refer_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_relationships",
                to="referral.referraltoken",
            ),
        ),
    ]
