from rest_framework.routers import DefaultRouter

from . import views

app_name = "api-v1"

# Initialize a DefaultRouter instance to automatically generate routes for the registered viewsets.
router = DefaultRouter()

router.register("adaboost", viewset=views.PredictorModelViewSet, basename="predictor")

# The urlpatterns variable will hold the URL patterns generated by the router.
urlpatterns = router.urls
