FROM python:3.11.4-slim-buster AS builder

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV HOME=/home/app
ENV APP_HOME=$HOME/core

RUN addgroup --system app && adduser --system --group app && mkdir -p $APP_HOME

WORKDIR $APP_HOME

COPY ./requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY ./entrypoint.dev.sh .
RUN apt-get update && apt-get install -y dos2unix && \
    dos2unix entrypoint.dev.sh && \
    chmod +x entrypoint.dev.sh

COPY . .

RUN chown -R app:app $APP_HOME

USER app

ENTRYPOINT ["/bin/bash", "./entrypoint.dev.sh"]
