# Generated by Django 4.2.16 on 2024-11-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("predictor", "0002_patient_predictionbydoctor"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PredictionByDoctor",
            new_name="DoctorPredictor",
        ),
        migrations.RenameModel(
            old_name="Predictor",
            new_name="PatientPredictor",
        ),
    ]
