from django.urls import path
from rest_framework.routers import DefaultRouter

from . import views

app_name = "api-v1"

# Initialize a DefaultRouter instance to automatically generate routes for the registered viewsets.
router = DefaultRouter()

router.register(
    "referral",
    viewset=views.ReferralViewset,
    basename="referral",
)
# The urlpatterns variable will hold the URL patterns generated by the router.
urlpatterns = router.urls

urlpatterns += [
    path(
        "get_relations/",
        views.ReferralRelationshipAPIView.as_view(),
        name="get-relations",
    ),
]
