from rest_framework.routers import DefaultRouter

from .. import views

# Initialize a DefaultRouter instance to automatically generate routes for the registered viewsets.
router = DefaultRouter()

router.register(
    "users",
    viewset=views.CustomUserViewSet,
    basename="users",
)
# The urlpatterns variable will hold the URL patterns generated by the router.
urlpatterns = router.urls
